version: '3.8'

services:
  app:
    build: .
    container_name: mongodb-app
    environment:
      MONGODB_URI: mongodb+srv://keenan:Mowgli4$@cluster0.oorsnye.mongodb.net/?appName=Cluster0
      MONGODB_DATABASE: myapp
      APP_ENV: production
      APP_LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    restart: unless-stopped
    stdin_open: true
    tty: true

